project_name: clog
release:
  github:
    owner: orangetangerine
    name: kubectl-clog
builds:
  - id: clog
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - arm64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/orangetangerine/kubectl-clog/pkg/version.version=
archives:
  - id: clog
    builds:
    - clog
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
