apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: clog
spec:
  version: "v0.1.1"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/orangetangerine/kubectl-clog/releases/download/v0.1.1/clog_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./clog"
      to: "."
    - from: LICENSE
      to: "."
    bin: "clog"
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/orangetangerine/kubectl-clog/releases/download/v0.1.1/clog_linux_arm64.tar.gz
    sha256: ""
    files:
    - from: "./clog"
      to: "."
    - from: LICENSE
      to: "."
    bin: "clog"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/orangetangerine/kubectl-clog/releases/download/v0.1.1/clog_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./clog"
      to: "."
    - from: LICENSE
      to: "."
    bin: "clog"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/orangetangerine/kubectl-clog/releases/download/v0.1.1/clog_darwin_arm64.tar.gz
    sha256: ""
    files:
    - from: "./clog"
      to: "."
    - from: LICENSE
      to: "."
    bin: "clog"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/orangetangerine/kubectl-clog/releases/download/v0.1.1/clog_windows_amd64.zip
    sha256: ""
    files:
    - from: "/clog.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "clog.exe"
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/orangetangerine/kubectl-clog/releases/download/v0.1.1/clog_windows_arm64.zip
    sha256: ""
    files:
    - from: "/clog.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "clog.exe"
  shortDescription: A new plugin
  homepage: https://github.com/orangetangerine/kubectl-clog
  caveats: |
    Usage:
      # just like kubectl logs ...
      $ kubectl clog ... 

    For additional options:
      $ kubectl clog --help
      or https://github.com/orangetangerine/kubectl-clog/blob/v0.1.1/doc/USAGE.md

  description: |
    This is a new plugin to colorize your kubectl logs. clog's just a wrapper of built-in kubectl logs, with same command usage, just replace `kubectl logs` with `kubectl clog` 
